### ISSUE TITLE
Optimized version of PSConv

### ISSUE THREAD

**Issue by rosinality** [d-li14/PSConv#2]
Hello, thank you for nice work!

It seems like that you made optimized version of PSConv as mentioned in the supplementary material of the paper. As it shows a great speedup, it could be very useful implementations for applying PSConv to various models.

Do you have a plan to release this optimized version of PSConv?

**Comment by d-li14** [comment]
Thanks for your interest! Actually it is optimized by the Intel hardware-related team, they may keep it as confidential for future Intel AI HW design. In short, I'm sorry to say that we don't have a recent plan for the speedup version release.

**Comment by rosinality** [comment]
That's too bad. Anyway, thank you for your work! I think it is a great progress for multiscale architectures.

**Comment by d-li14** [comment]
I have no access to this part except for the optimized statistical results. Probably seek support from @YaoAnbang.
