### ISSUE TITLE
I had a problem trying to use PSconv

### ISSUE THREAD

**Issue by bigonestep** [d-li14/PSConv#4]
I tested PSconv through a small code in the psconv.py file.
```
if __name__ == '__main__':
    net = PSConv2d(3, 3, 1, 1, 1, 1, 1, False)
    print(net)
    net = net.cuda()

    var = torch.FloatTensor(1, 3, 127, 127).cuda()
```

RuntimeError: The size of tensor a (129) must match the size of tensor b (131) at non-singleton dimension 3

**Comment by lewisli66** [comment]
How do you solve this problem,i meet the same problem.thank youfor your reply.
